### ISSUE TITLE
kap-key-cast not working for macOS v14

### ISSUE THREAD

**Issue by pixelchutes** [karaggeorge/kap-key-cast#10]
I was excited to see this plugin existed, but have unfortunately not been able to get it to work.

I've tried toggling the plugin on/off, restarting Kap, different settings, and even attempted some of the solutions from the list of Issues on the project _(e.g. disconnect 2nd monitor, etc)_

No matter what I've tried, I never see the keys presented in the final recording, regardless of `.webm`, `.mp4`, etc

Setup attempts using:

- macOS Sonoma `(v14.2.1)`
- Kap Version 3.6.0 `(3.6.0.1846)`

Help us @karaggeorge, you're our only hope!

**Comment by dzg** [comment]
I'm also on macos 14.5 ... and I get an error when trying this plugin:
```
Unhandled Promise Rejection
Error: Command was killed with SIGSEGV: /Users/zeev/Library/Application Support/Kap/plugins/node_modules/macos-key-cast/key-cast -s normal -t 0.5 -d 2
    at makeError (/execa/lib/error.js:59:11)
    at handlePromise (/execa/index.js:112:26)
    at runMicrotasks (<anonymous>)
    at async /Users/zeev/Library/Application Support/Kap/plugins/node_modules/macos-key-cast/index.js:45:20
```
