### ISSUE TITLE
Does not work with multiple monitors

### ISSUE THREAD

**Issue by detj** [karaggeorge/kap-key-cast#5]
Keys do not show up when multiple monitors are connected. I tried it with 2 monitors connected. The plugin was turned on, but key cast did not show up on screen at all. Although, the plugin works fine when the displays was mirrored.

**Comment by aqzhyi** [comment]
```
Unhandled Promise Rejection
Error: Command was killed with SIGSEGV (Segmentation fault): /Users/pleasurazy/Library/Application Support/Kap/plugins/node_modules/macos-key-cast/key-cast -s large -t 0.5 -d 724064980 -b {"bounds":[[921,86],[920,1114]]}
    at makeError (/execa/lib/error.js:59:11)
    at handlePromise (/execa/index.js:114:26)
    at async /Users/pleasurazy/Library/Application Support/Kap/plugins/node_modules/macos-key-cast/index.js:44:20
```

```sh
❯ npm install -g macos-key-cast
❯ key-cast

# Two monitors works a while after

[1]    7108 segmentation fault  key-cast
```

**Comment by Nitrodist** [comment]
Would love it if this issue was fixed 😻

**Comment by bable3** [comment]
Just for information : It works (on my macbook pro m2 - 2023) with multiple monitors. BUT it only works on my main mac screen.
