### ISSUE TITLE
Don't throw cancel error when stopping the recording

### ISSUE THREAD

**Issue by karaggeorge** [karaggeorge/kap-key-cast#7]
https://github.com/wulkano/Kap/issues/986

**Sentry Issue:** [KAP-9ER](https://sentry.io/organizations/wulkano-l0/issues/2264324144/)

**macOS version:**    Big Sur (11)
**Kap version:**      3.3.2

```
Unhandled Promise Rejection

CancelError: Promise was canceled
    at PCancelable.cancel (/p-cancelable/index.js:99:17)
    at Object.didStopRecording (/kap-key-cast/index.js:54:17)
    at /Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:56:28
    at Array.map (<anonymous>)
    at callPlugins (/Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:53:66)
    at cleanup (/Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:74:9)
    at Tray.stopRecording (/Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:218:5)
```

**Comment by antonijap** [comment]
Is this gonna be fixed? The issue is still there

**Comment by austriker27** [comment]
Can confirm issue exists on macOS 10.14.6 and Kap 3.3.2

**Comment by samundra** [comment]
Hi everyone,

Is there any workaround for this issue other than resetting everything?

**Comment by karansapolia** [comment]
Encountered this issue today. Seems like this has remained unresolved for some time now. @karaggeorge Let me know if it would help if I could work on this or a sub-part of it. Happy to help.
